### ISSUE TITLE
Build fails on Linux

### ISSUE THREAD

**Issue by ricardomatias** [ad-si/FlatCV#1]
I'm trying to build on Linux (Pop-OS 24.04) but it fails when running `make lin-build`:
```sh
c     flatcv.c   -o flatcv
/usr/bin/ld: /lib/x86_64-linux-gnu/crt1.o: in function `_start':
(.text+0x17): undefined reference to `main'
/usr/bin/ld: /tmp/ccdXkcWp.o: in function `fcv_apply_gaussian_blur':
flatcv.c:(.text+0xeb1): undefined reference to `exp'
/usr/bin/ld: /tmp/ccdXkcWp.o: in function `fcv_bw_smart':
flatcv.c:(.text+0x14fe): undefined reference to `sqrt'
/usr/bin/ld: /tmp/ccdXkcWp.o: in function `fcv_resize':
flatcv.c:(.text+0x1988): undefined reference to `floor'
/usr/bin/ld: flatcv.c:(.text+0x19a0): undefined reference to `floor'
/usr/bin/ld: flatcv.c:(.text+0x19b8): undefined reference to `ceil'
/usr/bin/ld: flatcv.c:(.text+0x19d0): undefined reference to `ceil'
/usr/bin/ld: flatcv.c:(.text+0x1ec4): undefined reference to `floor'
/usr/bin/ld: flatcv.c:(.text+0x1ed9): undefined reference to `floor'
/usr/bin/ld: /tmp/ccdXkcWp.o: in function `fcv_detect_corners':
flatcv.c:(.text+0x32f6): undefined reference to `sqrt'
/usr/bin/ld: flatcv.c:(.text+0x3331): undefined reference to `sqrt'
/usr/bin/ld: flatcv.c:(.text+0x341e): undefined reference to `asin'
/usr/bin/ld: /tmp/ccdXkcWp.o: in function `euclidean_distance':
flatcv.c:(.text+0x3ca5): undefined reference to `sqrt'
/usr/bin/ld: /tmp/ccdXkcWp.o: in function `fcv_extract_document_auto':
flatcv.c:(.text+0x519d): undefined reference to `pow'
/usr/bin/ld: flatcv.c:(.text+0x51d2): undefined reference to `pow'
/usr/bin/ld: flatcv.c:(.text+0x51ed): undefined reference to `sqrt'
/usr/bin/ld: flatcv.c:(.text+0x521f): undefined reference to `pow'
/usr/bin/ld: flatcv.c:(.text+0x5254): undefined reference to `pow'
/usr/bin/ld: flatcv.c:(.text+0x526f): undefined reference to `sqrt'
/usr/bin/ld: flatcv.c:(.text+0x52a1): undefined reference to `pow'
/usr/bin/ld: flatcv.c:(.text+0x52d6): undefined reference to `pow'
/usr/bin/ld: flatcv.c:(.text+0x52f1): undefined reference to `sqrt'
/usr/bin/ld: flatcv.c:(.text+0x5323): undefined reference to `pow'
/usr/bin/ld: flatcv.c:(.text+0x5358): undefined reference to `pow'
/usr/bin/ld: flatcv.c:(.text+0x5373): undefined reference to `sqrt'
/usr/bin/ld: flatcv.c:(.text+0x5393): undefined reference to `fmax'
/usr/bin/ld: flatcv.c:(.text+0x53b3): undefined reference to `fmax'
/usr/bin/ld: /tmp/ccdXkcWp.o: in function `fcv_foerstner_corner':
flatcv.c:(.text+0x66f5): undefined reference to `fmax'
/usr/bin/ld: flatcv.c:(.text+0x6725): undefined reference to `fmax'
/usr/bin/ld: /tmp/ccdXkcWp.o: in function `fcv_apply_matrix_3x3':
flatcv.c:(.text+0x81fb): undefined reference to `floor'
/usr/bin/ld: flatcv.c:(.text+0x8210): undefined reference to `floor'
/usr/bin/ld: /tmp/ccdXkcWp.o: in function `fcv_sobel_edge_detection':
flatcv.c:(.text+0x89a6): undefined reference to `sqrt'
/usr/bin/ld: /tmp/ccdXkcWp.o: in function `cartesian_to_polar':
flatcv.c:(.text+0x8b7c): undefined reference to `sqrt'
/usr/bin/ld: flatcv.c:(.text+0x8b9c): undefined reference to `atan2'
/usr/bin/ld: /tmp/ccdXkcWp.o: in function `sort_corners':
flatcv.c:(.text+0x9a24): undefined reference to `sqrt'
/usr/bin/ld: flatcv.c:(.text+0x9abc): undefined reference to `atan2'
collect2: error: ld returned 1 exit s
```

**Comment by OctopusET** [comment]
Ah just do 
```
gcc flatcv.c -lm -o flatcv
```
